An opinionated Emacs config intended for Neovim users with a IDE-like experience.  This config attempts to meld the quick, powerful editing conventions of Vim with the extensibility and power of Emacs along with aiming for modern development environment sensibilities.
* Requirements
This configuration assumes at least GNU Emacs 29.1 with built-in tree-sitter (=treesit=), LSP (=eglot=), and =use-package=.  It also assumes a build environment is setup and available to it for native builds of some packages.  In addition, it also currently assumes certain additional tools are installed such as specific tree-sitter language implementations and some LSP servers.
* Installation
Ensure you have Emacs, preferably 29.1 or later, installed in in the ~PATH~.

Checkout this repository into your home directory as src_sh[:exports code]{~/.emacs.d}:
#+begin_src sh
  git clone git@github.com:Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src

Make sure there aren't any other Emacs configs that could get picked up at src_sh[:exports code]{~/.emacs} or src_sh[:exports code]{~/.emacs.el}.

Start Emacs and wait for all the packages to install and compile.

Enjoy :)
