An opinionated Emacs config intended for Neovim users with a IDE-like experience.  This config attempts to meld the quick, powerful editing conventions of Vim with the extensibility and power of Emacs along with aiming for modern development environment sensibilities.
* Requirements
This configuration assumes at least GNU Emacs 29.1 with built-in tree-sitter (=treesit=), LSP (=eglot=), and =use-package=.  It also assumes a build environment is setup and available to it for native builds of some packages.  In addition, it also currently assumes certain additional tools are installed such as specific tree-sitter language implementations and some LSP servers.
* Installation
Ensure you have Emacs, preferably 29.1 or later, installed in in the =PATH=.

Checkout this repository into your home directory as =~/.emacs.d=:
#+begin_src sh
  git clone git@github.com:Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src

Make sure there aren't any other Emacs configs that could get picked up at =~/.emacs= or =~/.emacs.el=.

Start Emacs and wait for all the packages to install and compile.

Enjoy :)
* Emacs Installation
** Linux
*** Debian (stable)
Ensure stable backports repository is enabled.  If it's not, enable it with—assuming you're using Debian 12 Bookworm:
#+begin_src bash
  echo -e "Types: deb\nURIs: http://deb.debian.org/debian\nSuites: bookworm-backports\nComponents: main contrib\nSigned-By: /usr/share/keyrings/debian-archive-keyring.gpg" > /etc/apt/sources.list.d/backports.sources
#+end_src
or
#+begin_src bash
  echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list
#+end_src
Install Emacs and dependencies:
#+begin_src bash
  apt install git build-essential curl
  apt install -t bookworm-backports emacs
#+end_src
Install this config:
#+begin_src bash
  git clone git@github.com/Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src
Launch Emacs.
*** Arch Linux
Install Emacs and dependencies:
#+begin_src bash
  pacman -S emacs-nativecomp git base-devel curl
#+end_src
Install this config:
#+begin_src bash
  git clone git@github.com/Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src
Launch Emacs.
*** Gentoo
Assuming you're using a desktop profile, add the following portage use flag configuration in a file under =/etc/portage/package.use/=, probably named something like =emacs=:
#+begin_example
  >=app-editors/emacs-29.1 harfbuzz imagemagick jit json libxml2 source sqlite toolkit-scroll-bars tree-sitter webp xwidgets
  >=sys-devel/gcc-12.3.1 jit
#+end_example
Install Emacs:
#+begin_src bash
  sudo emerge -avn app-editors/emacs dev-vcs/git net-misc/curl
#+end_src
Install this config:
#+begin_src bash
  git clone git@github.com/Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src
And launch Emacs.
*** Guix
#+begin_src bash
  guix install emacs
#+end_src
Really.  That's it.  It even has ahead-of-time native compilation enabled.
#+begin_src
  git clone git@github.com/Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src
You still need to grab this config and launch Emacs though.
*** Fedora
Install Emacs and dependencies:
#+begin_src bash
  sudo dnf group install "Development Tools"
  sudo dnf install emacs
#+end_src
Install this config:
#+begin_src bash
  git clone git@github.com/Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src
Launch Emacs.
*** Ubuntu
Install Emacs and dependencies:
#+begin_src bash
  sudo apt install emacs git build-essential curl
#+end_src
Install this config:
#+begin_src bash
  git clone git@github.com/Ryan-B-W/vimacs.app.git ~/.emacs.d
#+end_src
Launch Emacs.
*** Nix
Sorry, but you're on your own.  Then again, you expected as much.  Didn't you?
** Mac OS
Using Homebrew:
#+begin_src bash
  brew tap railwaycat/emacsmacport
  brew install emacs-mac --with-modules
  ln -s /usr/local/opt/emacs-mac/Emacs.app /Applications/Emacs.app
#+end_src
[[https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#on-macos][See also the guide from Doom Emacs where this was unapologeticlly taken from]].
** Windows
Follow [[https://learn.microsoft.com/en-us/windows/wsl/install][the official]] instructions for getting setup with WSL2.  For distributions, latest Debian stable—Debian 12, Bookworm at time of writing—with the stable backports suite enabled is recommended by the author of this config.  If using Debian under WSL2, follow the instructions above for installing under Debian.  You can install Windows native Emacs but your mileage will vary and some things may not be available.  Importantly, Windows native filesystem performance is fairly poor and will noticeably impact performance when doing things like git operations and file searches.  In addition, Emacs performance under Windows in general has historically been pretty poor in general if perhaps tolerable.  However, accessing Windows filesystem files from within WSL2 has even worse performance than native Windows filesystem access and is a compelling reason to use Windows native Emacs instead of WSL2.  The maintainer of this configuration doesn't use Windows so testing is up to the users.
If you opt for Windows native Emacs, see the official [[https://www.gnu.org/software/emacs/manual/html_node/efaq-w32/index.html][Emacs FAQ for MS Windows]].  As above, checkout this repository as the Emacs init directory using git.
** Other
You probably know what you're doing.  Good luck.
* Todo
 - [ ] Make =Escape= and =C-g= equivalent
 - [ ] Fix diff-hl not syncing with magit changes
 - [ ] Have some way of reliably managing external dependencies, such as language servers, across all supported platforms
 - [ ] Make initial startup much quieter by silencing expected native- and byte-compilation warnings
 - [ ] Add configurable grammar checker
 - [ ] Add optional AI assistant and completion
   - This is contingent on finding an /actually/ legally safe language model, not simply one that claims to be safe but has training data of questionable at best legality
 - [ ] Integrate with Emacs's built in ~customize~ UI for configuring Vimacs.app
 - [ ] Add more language/tool/platform specific helpers and tools like python virtual environment management
 - [ ] Add more communications stuff like a properly integrated IRC setup, Matrix client, mail client, RSS reader, etc.
   - There are a few of a couple of those built-in but they need to be configured and a couple have packages that are better than the built-in option
 - [ ] Add more media stuff like music, video, and podcast listening/watching
 - [ ] External CalDAV/WebCAL/ICS compatible calendar integration
 - [ ] Determine if the version of Slime helper from Quicklisp should be replaced with the Slime package from NonGNU Elpa, Melpa Stable, Melpa, or if it is still the best option
 - [ ] Add introduction tutorial for new users who may not be familiar with Emacs and Vim
 - [ ] Document the various features of Vimacs.app and how to use them
   - This would serve as both a way for new users to get familiar with what the configuration has to offer as well as an entrypoint into the relevant documentation for the packages that provide that functionality
 - [ ] Add binding for opening attachment(s) of Org Roam node at point
